image: node:latest

pages:
  stage: deploy
  script:
  - npm install
  - node ./node_modules/@angular/cli/bin/ng build --aot=true --environment=prod --sourcemap=false --base-href="https://spaz.gitlab.io/angular-worldwind/"
  artifacts:
    paths:
    - public
  only:
  - master